// reborrow of field
// rustc +nightly 37.rs -Z polonius=next
// It is an example from the thesis "Formal Verification of Rust programs by functional translation", which demonstrates the imprecision of reborrow in Polonius. Since our borrow checking is based on Polonius, this program is rejected by our borrow checker.

struct pair {
    first: i32,
    second: i32,
}

fn main(){
    let mut p: pair = pair { first: 12, second: 14 };
    let mut x: &mut pair = &mut p;
    let mut y: &mut i32 = &mut (*x).first;
    // p.second = 15; // It is an error here due to the imprecision of constraint generated by reborrow which considers that x is being borrowed. To make it precise, we need to add p.first to the region of y instead of adding p which is the cause of this imprecision.
    *y = 20;
}
